### ISSUE TITLE
Results cannot be displayed in table format like chatGPT.

### ISSUE THREAD

**Issue by myh-st** [arbs-io/vscode-openai-docs#1]
Results cannot be displayed in table format like chatGPT.

![image](https://user-images.githubusercontent.com/37788058/227540418-af79d94c-6b6c-4946-b0a6-51383e4782b7.png)

on Genie extension ( genieai.chatgpt-vscode ) can be displayed in a table format

<img width="490" alt="image" src="https://user-images.githubusercontent.com/37788058/227540819-3055d736-9978-463d-a7c1-5194f9c010d0.png">

**Comment by arbs-io** [comment]
Hi @myh-st,

I'm sorry for not getting back to you sooner. Unfortunately, I'm travelling at the minute and have limited access.

I've resolved the rendering in the latest version, 1.0.7 (released a few minutes ago). So your existing conversation will render correctly now. However, the render results must be formatted without borders for the minute. I'll make them look presentable soon. I didn't want to go with the default styling. 

![image](https://user-images.githubusercontent.com/71968891/227745351-33736ced-ed90-4fb8-b711-b43878ea48da.png)

**Comment by arbs-io** [comment]
will raise a feature to render a data grid (rather than table), which is themed
