### ISSUE TITLE
Azure OpenAI Chat Completion in GA - API version 2023-05-15

### ISSUE THREAD

**Issue by rabbyn** [arbs-io/vscode-openai-docs#13]
Hi @arbs-io , from the latest annoucement on [Microsoft Azure Open AI](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/whats-new#may-2023) it's written that if we are currently using the 2023-03-15-preview API, it's recommended to migrate to the GA 2023-05-15 API. 

I tried to change it on VScode-openai settings but it's not possible to add an new entry in this dropdown menu. 
...and thanks again for your extension it rocks ! 

![image](https://github.com/arbs-io/vscode-openai-docs/assets/72968975/4870c51a-c3a1-48d6-8300-969c001957ac)

**Comment by arbs-io** [comment]
Thanks for highlighting, I will get the new api added and default in a few hours.

**Comment by arbs-io** [comment]
Please upgrade to version 1.1.8 (close vscode and restart -> reload)

**Comment by arbs-io** [comment]
please rate the extension, it really helps me out 😃

**Comment by rabbyn** [comment]
Thanks @arbs-io for your quick action. I already rated long time back in VS code marketplace, I even give my little contribution earlier today (sponsor) :)

**Comment by arbs-io** [comment]
Thank you, @rabbyn, very, very much appreciated!
