### ISSUE TITLE
Support export conversation history as markdown

### ISSUE THREAD

**Issue by madawei2699** [arbs-io/vscode-openai-docs#14]
This is a feature request, it will be helpful if it can support export conversation history as markdown.

**Comment by arbs-io** [comment]
Very good suggestion. I'll add the feature over The Weeknd. There will be a new version available on Monday.

**Comment by arbs-io** [comment]
This feature has been added in version 1.1.10

**Comment by asifm** [comment]
Sorry if I'm missing something obvious, but I can't find the command to export conversation history as markdown. (I'm using version 1.2.1)

**Comment by asifm** [comment]
Found it right after posting my comment. For anyone else looking for the feature: Open the extension's sidebar and click on the three dots to the right of a conversation session summary. There you'll find "Open Markdown".
