### ISSUE TITLE
Custom Source Integration : How to ?

### ISSUE THREAD

**Issue by rabbyn** [arbs-io/vscode-openai-docs#15]
Hello @arbs-io , thanks again for this great extension, I was trying to use the "Custom Source Integration" but on my VScode I can't see the "file embedding" panel as shown on your readme screenshot below. 

![image](https://github.com/arbs-io/vscode-openai-docs/assets/72968975/17f4a3cd-dc8b-49b4-b975-820a1ab87c7b)

As well would it be possible to get the "**CHANGELOG**" of the extension **available directly from VScode** as shown below ? Thanks

![image](https://github.com/arbs-io/vscode-openai-docs/assets/72968975/f5c77ab5-0818-4586-abed-cc0f2cd43fc3)

**Comment by arbs-io** [comment]
Hi @rabbyn 
I've added the changelog so the next release(s) will have high-level commit messages. This will explain why the release was made. 
Re: embeddings, it's close, but I had to pack some utils in [extract-text-content](https://github.com/arbs-io/extract-text-content/) and have struggled with cjs~esm when read binary files in the vscode extension. It's getting closer but it has taken a lot longer than expected (the openai and vscode part were quick, the text extraction has taken much longer.

**Comment by rabbyn** [comment]
Hi @arbs-io , ok cool thanks ! I'm looking forward for the embedding feature, that will be awesome.

PS : I just made my Github sponsorship recurrent :  the work you put on building this extension and the effort you do to always make it better deserve it ! .....I'm using it everyday for my work and I shared it all will my colleagues

**Comment by arbs-io** [comment]
Hi @Mr-Guillaume 
Very sorry for the delay. The feature will be released in version 1.3.2 (released in the next couple of hours). It will support standard markdown, HTML, text and docx.
Unfortunately, I had to pull PDF support. But, it's a priority and I have a prototype working well so hopefully it will be added over the weekend.

**Comment by rabbyn** [comment]
Hi @arbs-io, cool thanks, it's ok for the PDF support we can wait. Actually I just tested (from VS Code insiders) and I don't see the way to upload custom source as shown below ?

![image](https://github.com/arbs-io/vscode-openai-docs/assets/72968975/8ef008d4-7d34-4baa-8dfd-0e436d388fde)

I setup all the necessary pre-requisite for this feature , could it be because my running VS Code insiders ?

![image](https://github.com/arbs-io/vscode-openai-docs/assets/72968975/649ce95a-ee5d-4e49-88bc-fe7d60eb61b5)
![image](https://github.com/arbs-io/vscode-openai-docs/assets/72968975/fb474428-ba19-4323-803c-e1ba2d516166)
![image](https://github.com/arbs-io/vscode-openai-docs/assets/72968975/17cd1128-7812-472a-818b-77cf00c4cc8e)

**Comment by arbs-io** [comment]
If you drop a file from explorer onto the area it should automatically index and display. Does that not happen?

**Comment by rabbyn** [comment]
Hi @arbs-io ,oh ok sorry ; i checked every possible cause but didn't try drag and drop  🤔

PS: maybe just put a line to explain that in the user guide / "how to use section" from the extension page, i believe i will not be the last one to stay stuck on that matter 😜

**Comment by arbs-io** [comment]
Great! Will do. I'll also add a few buttons to pull local resources and/or from the web.
