### ISSUE TITLE
Request for Feature: Clear All Conversation History

### ISSUE THREAD

**Issue by kavehsfv** [arbs-io/vscode-openai-docs#16]
There isn't an option to delete all conversation history at once. It would be really helpful if we could have a feature that allows us to clear previous conversations with just one click. This would make it easier for us to manage our chat history.

**Comment by arbs-io** [comment]
Hi @kavehsfv 
Great idea I will add a clear all in the next release 1.3.3

**Comment by kavehsfv** [comment]
@arbs-io Thank you.

**Comment by arbs-io** [comment]
Hi @kavehsfv 
I've added the delete all conversations button on the conversation toolbar. Closing as completed

**Comment by kavehsfv** [comment]
It works nice, thank you :)
