### ISSUE TITLE
Also add Down Arrow to restore written Text

### ISSUE THREAD

**Issue by g4borg** [arbs-io/vscode-openai-docs#17]
In General Chat, Up Arrow is used to get to the previous text, however accidentally hitting that button deletes everything that was currently written.

That is kind of a shame, as not only does this disable the ability in the future to use arrow keys in a text edit field, if you ever expand the editing capabilities, but also, because all written things can be lost, without the ability to restore them with CTRL+Z

Since this forces one to write it in an external editor to be safe, for me this kind of devalues the input field in it's usage.

**Comment by arbs-io** [comment]
Hi @g4borg 
Agreed, I've changed the functionality to require Shift and UpArrow to avoid mistaking deleting content. 

"Enter+Shift for a newline and Enter+ArrowUp restore previous value"

This will be added in 1.3.2 later today

**Comment by g4borg** [comment]
I just tried it and saw your hint text in the input field.
I think you meant to write

"Shift+Enter for a newline, Shift+ArrowUp restores previous value"

or

"Shift+Enter for a newline and Shift+ArrowUp to restore previous value"

"Enter+ArrowUp" does not make sense ;-) 

Anyway thank you very much for this improvement.

**Comment by arbs-io** [comment]
Good catch. Thanks for highlighting. I'll correct the message in the next release
