### ISSUE TITLE
Request for feature: Remove key validation for Open AI (BYOK)

### ISSUE THREAD

**Issue by zukwung** [arbs-io/vscode-openai-docs#18]
Hi, great plugin :) 

I am trying to get [credal.ai](https://www.credal.ai/) to work with the plugin, but the API key validation prevents me from doing so, even though [the API is compatible with OpenAI's API](https://credalai.notion.site/OpenAI-Drop-in-API-0ef7cfd18a7c4aa5a0388d77eb2b4a3a). I'm sure there will be more openAI compatible services in the future. 

My request is if its possible to turn off the key validation, or add a setting to turn off the key validation. Thanks!

**Comment by arbs-io** [comment]
Hi @zukwung 
Understood, it's similar to the oauth2 protect issue. I'll get this changed in the next release (over the weekend). I've not used credal.ai will look at the service and ensure it's supported going forward.

**Comment by arbs-io** [comment]
Hi @zukwung 
I've checked the service, and it looks great, I like the concept.
I've change vscode-openai to accept auth tokens. However, Credal doesn't provide a model list so selection of service(s) isn't possible. Instead, I'll add a custom manual configuration without "helper" features which should allow you to manually configure the service. I will need to implement to test if this approach will actually work (I don't know how customised the service is but it seems feasible from the documentation).
I'm closing this issue for now as the auth has been changed. I've raised an internal feature and hope to have this feature added within the week.

**Comment by ravintpillai** [comment]
Hey guys! Ravin here - founder of Credal.ai - just noticed this issue as we had some traffic to our website from the link you posted :) When you say Credal doesn't provide a model list - can you clarify exactly how you would want that?

**Comment by arbs-io** [comment]
Hey @ravintpillai,

just dropped you a mail. Would it be possible to include list model API. I presume your portal is already doing this to allow users to select a gpt4+ model.
https://platform.openai.com/docs/api-reference/models

appreciate this would be a change on your side and happy to add a fixed list for now. I'll add Credal as a listed service provider in the extension to make the configuration.

**Comment by ravintpillai** [comment]
Awesome got it thanks, should have this live for you very shortly!
