### ISSUE TITLE
Request to add a setting button

### ISSUE THREAD

**Issue by kavehsfv** [arbs-io/vscode-openai-docs#19]
Hi
Could you please add a setting button in the menu?
For example if I want to change my model, I should go to the extension panel, find your extension and go to the setting.

**Comment by arbs-io** [comment]
Hi @kavehsfv 
I'll look into the best way to quick-switch models on existing setups.

**Comment by arbs-io** [comment]
Hi @kavehsfv 
I've added a "Change Models" selection on the Registration quick-pick. This will allow you to change the model without having to re-registering the whole service provider.

Available in version 1.3.8

![image](https://github.com/arbs-io/vscode-openai-docs/assets/71968891/f575aa13-4d99-4d8d-be92-3e8d8f846ed0)

**Comment by kavehsfv** [comment]
Works great, thank you!
