### ISSUE TITLE
Type Message box and result in Chat

### ISSUE THREAD

**Issue by myh-st** [arbs-io/vscode-openai-docs#2]
I think type message box should be able to take a newline. Rather than combining messages into a single set

Here's sample coding

<img width="457" alt="image" src="https://user-images.githubusercontent.com/37788058/227858891-4516c318-06d0-47a4-a40d-1dca48dbd3e2.png">

<img width="730" alt="image" src="https://user-images.githubusercontent.com/37788058/227858758-623a8124-4546-4ce4-9d4f-24d57f148e65.png">

The result should be

<img width="483" alt="image" src="https://user-images.githubusercontent.com/37788058/227859127-3eed717a-4ddf-400e-a92a-a841a88bd773.png">

Maybe to create a new line in the message box, use the shortcut key Shift + Enter or configure a new line shortcut key in the extension settings. Thank you for taking your time and helping to improve the previous issue.

**Comment by arbs-io** [comment]
Many thanks for raising. Complete agree this should work. I'll add the feature soon. I'm traveling at the minute but will try and get it sorted this soon. As I don't have full access to my dev environment.

**Comment by myh-st** [comment]
Request copy button to copy only code

![image](https://user-images.githubusercontent.com/37788058/228766868-a7378fc4-2d58-40cd-a854-2e1685ccb442.png)

**Comment by arbs-io** [comment]
I've included multi-line input and conversation continuation in the latest release.
So I'll close this issue.

But, I have opened a feature to create a virtual document (for the code) extracted from any conversation.
Thanks again for taking the time to provide meaningful feedback. It's much appreciated.
