### ISSUE TITLE
cannot find upgrade button

### ISSUE THREAD

**Issue by bbb324** [arbs-io/vscode-openai-docs#20]
there isn't any upgrade button

![image](https://github.com/arbs-io/vscode-openai-docs/assets/3301789/fd399823-6bb0-4e85-8c73-6c4f3487ba51)

![image](https://github.com/arbs-io/vscode-openai-docs/assets/3301789/317f9214-3769-4147-9ba7-758960ec6820)

**Comment by arbs-io** [comment]
Which version of the extension is showing as installed?

Just noticed you closed already.
