### ISSUE TITLE
Request to add search feature in chat page

### ISSUE THREAD

**Issue by kavehsfv** [arbs-io/vscode-openai-docs#21]
It would be a great addition if you could implement a search feature in the chat page using 'ctrl + F'.
This feature would be helpful for users who want to quickly find a specific word or phrase in the previously generated chats.

**Comment by arbs-io** [comment]
Great idea! Will add it to the backlog. It might take some time as I'm in the middle of other features. 
Do you think a global (all chats) or local (scoped) would be better?

**Comment by kavehsfv** [comment]
Thanks,
I was considering the local one when I was looking for a word, but it'd be great if you add global search with 'Ctrl+Shift+F' too. 
I appreciate your consideration.

**Comment by arbs-io** [comment]
I've added search (Ctlr+F) to the conversation panel. Available in v1.4.0

This is a local search for now.  I'll look into a global filter/search, but implementing that will take longer.
