### ISSUE TITLE
Make embedded model optional again

### ISSUE THREAD

**Issue by g4borg** [arbs-io/vscode-openai-docs#23]
At the moment, embedded model selection when setting up vscode-openai with "Azure-OpenAI" is the 4th step

However in setups, where the Azure deployment does not have activated this feature or you have no access, you get stuck on this for new installs, nothing I enter works.

On existing installs, the value in the user settings is "setup-required", but the plugin still works properly.

Since without finishing the wizard, the secret cannot be written into the secret storage, new OpenAI installs cannot overcome this step in such a situation.

**Comment by g4borg** [comment]
(The workaround for affected users is downgrading to 1.2.3, which has only 3 steps)

**Comment by arbs-io** [comment]
Thanks for reporting. I will get a patch out to ignore model selection if no models available

**Comment by arbs-io** [comment]
This has been resolved in version 1.3.9
