### ISSUE TITLE
Chat UI and menu not loading

### ISSUE THREAD

**Issue by paveldokov** [arbs-io/vscode-openai-docs#4]
Every time I start VS code (on a MacBook) it displays a red message: "Azure-OpenAI Invalid Api-Key" in the status bar. Entering the API key does not remove the red message on the status bar. 
Nonetheless, if I copy text and run command from 'Show and run command' menu, it connects to API and gives a response. (I need to enter API key every time before it actually starts functioning).
Additionally, it does not load the UI components - Chat, menu, etc.

I am connecting to Azure OpenAI service.

**Comment by arbs-io** [comment]
Will get this fixed as a priority. Hope to have a fix released later today.

Many thanks for taking the time to raise the issue

**Comment by arbs-io** [comment]
Hi @paveldokov 
I've changed the setting configuration and added helpful hints on the status bar. See [detecting-issues](https://github.com/arbs-io/vscode-openai-docs#detecting-issues) for more info.

Could you please re-try using the latest version:

I've developed this change on MacOS (M2) and can confirm it's working as expected on azure and native openai

**Comment by paveldokov** [comment]
Works great! 
Thanks
