### ISSUE TITLE
support of Azure Open AI gtp-4 model ?

### ISSUE THREAD

**Issue by rabbyn** [arbs-io/vscode-openai-docs#6]
Hello @arbs-io , thanks for this contribution i just managed to connect Azure Open AI gpt-35-turbo (version 0301) and it's what I was looking ; I will definitively give it a 5 stars rating and a good review on VS Code marketplace . 

On the other end I couldn't connect Azure Open AI gpt-4 , is it supported by this version of the extension or not yet ? if yes is there any tricks to get it work with gtp-4 ? Thanks a lot

**Comment by arbs-io** [comment]
Hi @rabbyn 
Many thanks for take the time to report the issue. Technically gpt4 is supposed. But the persona doesn't reflect the model. I will resolve this asap. To change the default model update the model in settings. You can search for "vscode-openai" in the vscode settings.

**Comment by rabbyn** [comment]
Hi @arbs-io , I'm looking forward for that. Thanks for your reply and the effort you put creating this VS Code extension

**Comment by arbs-io** [comment]
Hi @rabbyn 
Great to hear that you're using Azure! To point to your GPT4 deployment, all you need to do is update the deployment to the gpt4 instance. The gpt4 model is only available by request from Microsoft. Do you have the request for link?

With Azure, you have the flexibility to set this to anything as long as the deployment and base model is correctly specified. This makes it easy for you to use the Azure service and get started with your project quickly. Let me know if there's anything else I can help you with!

**Comment by rabbyn** [comment]
Hi @arbs-io , yes I already had my gpt4 deployment ready but it was not working when I tried the extension 2 days ago. I seems that you fix the issue with the persona now.... and I confirm it works for me !!  Thanks a lot !

PS : you just got a 5 stars on Visual Studio Marketplace from me 👍 

![image](https://user-images.githubusercontent.com/72968975/231313465-a4d3481a-6fe2-4609-ace3-d9e7f4f4c527.png)
