### ISSUE TITLE
Authentication failed: 403 forbidden

### ISSUE THREAD

**Issue by Muenzi1** [arbs-io/vscode-openai-docs#7]
I tried to connect to my Azure Open AI ressource (west europe hosted), but authentication constantly failed with the following error message:

`unexpected error: Please report the following details to github (remove any sensitive data). {"message":"Request failed with status code 403","name":"Error","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"OpenAI/NodeJS/3.2.1","Authorization":"Bearer 0a427f4bce77********************","api-key":"0a427f4bce77********************"},"method":"get","params":{"api-version":"2022-12-01"},"url":"https://RESOURCE_NAME.openai.azure.com/openai/models"},"status":403}`

Do you have any idea what could be the reason? I checked the token multiple times and it should be fine.

**Comment by arbs-io** [comment]
Hi @Muenzi1 
Could you change the api version to "2023-03-15-preview". Seem that it's set to stable the previous version which doesn't support the required APIs.

**Comment by arbs-io** [comment]
Please see: https://marketplace.visualstudio.com/items?itemName=AndrewButson.vscode-openai&ssr=false#configuring-azure

**Comment by Muenzi1** [comment]
Hi, yes that was my assumption as well. But, I thought that this API version is not available for resources outside the US.

Is there a place to check for available API versions of the resource? When I enter the playground and click on "generate code" it always generates a snippet using the 2022-12-01 API Version.

**Comment by arbs-io** [comment]
I think it is available now. 

Unless you have a need to use Europe, I would suggest using us-East for now. Azure is rolling out functionality first to the region. Eu is often a few months behind. When the service is ga then I'd expected parity.

I work for a large enterprise used in emea and we're using us-east for the minute because of the feature delay (it was also unofficial advised my our ms reps on the openai team).

Try the preview api it should be working now (I think it must have been enabled last week)

**Comment by Muenzi1** [comment]
Alright, I will check this on Monday. 

For legal reasons we are not allowed to use resources outside EU, currently. But I will keep this in mind.

**Comment by Muenzi1** [comment]
So, I tried the api-version 2023-03-15, but it does not change anything to me:

`unexpected error: Please report the following details to github (remove any sensitive data). {"message":"Request failed with status code 403","name":"Error","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"OpenAI/NodeJS/3.2.1","Authorization":"Bearer 8631f0513b9947******************","api-key":"8631f0513b9947******************"},"method":"get","params":{"api-version":"2023-03-15-preview"},"url":"https://RESOURCE_NAME.openai.azure.com/openai/models"},"status":403}`

**Comment by adumont** [comment]
> So, I tried the api-version 2023-03-15, but it does not change anything to me:
> 
> `unexpected error: Please report the following details to github (remove any sensitive data). {"message":"Request failed with status code 403","name":"Error","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"OpenAI/NodeJS/3.2.1","Authorization":"Bearer 8631f0513b9947******************","api-key":"8631f0513b9947******************"},"method":"get","params":{"api-version":"2023-03-15-preview"},"url":"https://RESOURCE_NAME.openai.azure.com/openai/models"},"status":403}`

Where do you export this log from? I have another issue, and I can see no log anywhere.

**Comment by Muenzi1** [comment]
I just found out that my bug resulted from an active firewall, that blocked my authentication. After adding my client to the firewall exceptions, authentication was fine.
