### ISSUE TITLE
Resource not found: check baseurl, api version or deployment name (Azure)

### ISSUE THREAD

**Issue by adumont** [arbs-io/vscode-openai-docs#8]
Hi,
I have an Azure OpenAI instance, and I'm failing to setup this extension. I believe all the values are correctly setup. Authentication is fine, but I still get a "AzureInstanceName - not found" error when sending a new message in a new conversation.

The toast/popup in the lower right corner says "Resource not found: check baseurl, api version or deployment name"

Deployment name, model name and version are correctly configured (copy-paste from the Azure OpenAI Playground "view code"). (Also I have added /openai to the instance name, as explained in the docs).

Is there any way to get some more log to find out what the problem can be?

**Comment by arbs-io** [comment]
Hi @adumont 

Are you using west-eu? I've just checked and the chat API still isn't available in region. Feature on azure preview are being rolled out in east-us first. Currently there is a 2-3 month lead time. Are you able to switch regions?

**Comment by adumont** [comment]
Indeed I was using a deployment in West EU, and Chat isn't available yet
here (sigh). I'll try to deploy in East US and report back here. Thanks for
the help.

**Comment by adumont** [comment]
Ok, indeed deploying an openai gpt-35-turbo in East US works! The model isn't available in West EU region yet.

```
    "vscode-openai.serviceProvider": "Azure-OpenAI",
    "vscode-openai.baseUrl": "https://my-instance-name.openai.azure.com/openai",
    "vscode-openai.azureApiVersion": "2023-03-15-preview",
    "vscode-openai.azureDeployment": "gpt-35-turbo-v0301",
    "vscode-openai.defaultModel": "gpt-35-turbo",
```

Thanks :)!
